---
# - name: deployment caddy
#   hosts: web 

#   tasks:
  - name: Ensure dependencies are installed.
    ansible.builtin.apt: name={{ item }} state=present
    loop:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - gnupg2
      - curl


  - name: Add Caddy apt key.
    ansible.builtin.apt_key:
      url: "{{ caddy_apt_gpg_key }}"
      id: 65760C51EDEA2017CEA2CA15155B6D79CA56EA34
      state: present
    register: add_repository_key
    ignore_errors: "{{ caddy_apt_ignore_key_error }}"

  - name: Add Caddy repository.
    ansible.builtin.apt_repository:
      repo: "{{ caddy_apt_repository }}"
      state: present
      update_cache: true
  - name: Install Caddy
    package:
      name: "{{  caddy_package }}"
      state: "{{ caddy_package_state }}"

  - name: restart caddy
    service: "name=caddy state={{ caddy_restart_handler_state }}"
...